# .streamlit/secrets.toml

public_gsheets_url = "https://docs.google.com/spreadsheets/d/1QHjQUA1_esa7uKlve-JW7yr9O9r2R6uh5vEgiiln3NE/edit#gid=0"
public_gsheets2_url = "https://docs.google.com/spreadsheets/d/1QHjQUA1_esa7uKlve-JW7yr9O9r2R6uh5vEgiiln3NE/edit#gid=980071778"
public_gsheets3_url = "https://docs.google.com/spreadsheets/d/1QHjQUA1_esa7uKlve-JW7yr9O9r2R6uh5vEgiiln3NE/edit#gid=841705233"